theme="journey"
languageCode = "en-us"
title = ""
baseurl = "http://midhunkrishna.in"
[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]
[permalinks]
  posts = "posts/:year/:month/:title/"